[build]
target = "target.json"
rustflags = [
    "-Z", "unstable-options", 
    "-C", "strip=debuginfo",
    "-C", "split-debuginfo=packed"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
