[workspace]
members = [
    "kernel",
    "libx64",
    "kcore",

    "bitfield",
    "interrupt_list",
    "qemu_logger",
    "page_mapper",
    
    "drivers/pic",
    "drivers/vga",
    "drivers/serialuart16550",
]
