[workspace]
members = [
    "kernel",
    "libx64",
    "kcore",

    "utils/bitfield",
    "utils/interrupt_list",
    "utils/qemu_logger",
    
    "drivers/page_mapper",
    "drivers/scheduler",
    "drivers/pic",
    "drivers/vga",
    "drivers/serialuart16550",
]
