[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["libx64", "kcore"]

[features]
qemu = []

[dependencies]
bootloader = "0.9"
bitflags = {version="1", default-features=false}

libx64 = {path = "libx64"}
kcore = {path = "kcore"}

alt-x86_64 = {package="x86_64", version="0.14"}


[package.metadata.bootimage]
run-args = ["-serial", "vc"]
test-args = ["-serial", "stdio"]
