[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["libx64", "kcore", "bitfield", "pic"]

[features]
qemu = []
gdb = []

[dependencies]
bootloader = "0.9"
bitflags = {version="1", default-features=false}

libx64 = {path = "libx64"}
kcore = {path = "kcore"}
pic = {path = "pic"}

alt-x86_64 = {package="x86_64", version="0.14"}


[package.metadata.bootimage]
#run-args = ["-serial", "stdio", "-s", "-S"]
run-args = ["-serial", "stdio"]
test-args = ["-serial", "stdio"]

# [target.'cfg(feature="gdb")'.package.metadata.bootimage]
# run-args = ["-serial", "stdio"]
