[workspace]
members = [
    "kernel",
    "libx64",
    "kcore",  
    "kalloc",
    "bootloader",

    "utils/bitfield",
    "utils/interrupt_list",
    "utils/qemu_logger",
    
    "drivers/page_mapper",
    "drivers/scheduler",
    "drivers/pic",
    "drivers/keyboard",
    "drivers/vga",
    "drivers/vesa",
    "drivers/serialuart16550",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
overflow-checks = true
