[workspace]
members = [
    "kernel",
    "libx64",
    "kcore",
    
    "bootloader",
    "bootloader/tests/runner",
    "bootloader/tests/test_kernels/default_settings",
    "bootloader/tests/test_kernels/map_phys_mem",
    "bootloader/tests/test_kernels/higher_half",
    "bootloader/tests/test_kernels/pie",

    "utils/bitfield",
    "utils/interrupt_list",
    "utils/qemu_logger",
    
    "drivers/page_mapper",
    "drivers/scheduler",
    "drivers/pic",
    "drivers/keyboard",
    "drivers/vga",
    "drivers/serialuart16550",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
overflow-checks = true
