cargo-features = ["workspace-inheritance"]

[package]
name = "kio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kcore = { workspace = true }
