[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name="kernel"
test=false

[features]
qemu = []
gdb = []

[dependencies]
bootloader = {version="0.9", features=["map_physical_memory"]}
bitflags = {version="1", default-features=false}


libx64 = {path = "../libx64"}
kcore = {path = "../kcore"}
interrupt_list = {path = "../interrupt_list", features=["libx64"]}

log = {version="0.4", default-features=false, features=["max_level_trace"]}
qemu_logger = {path = "../qemu_logger"}

pic = {path = "../drivers/pic"}
vga = {path = "../drivers/vga"}
serialuart16550 = {path = "../drivers/serialuart16550"}

[package.metadata.bootimage]
run-args = ["-serial", "stdio"]
test-args = ["-serial", "stdio"]
